name: flutter_weather_app
description: "A new Flutter project."
publish_to: 'none'

# https://developer.android.com/studio/publish/versioning
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  collection: ^1.18.0
  cupertino_icons: ^1.0.8
  dio: ^5.4.3+1
  firebase_core: ^2.27.2
  firebase_auth: ^4.19.6
  flutter_dotenv: ^5.1.0
  flutter: { sdk: flutter }
  flutter_mobx: ^2.2.1+1 #
  mobx: ^2.3.3+2 #
  gap: any
  get_it: ^7.7.0
  path_provider: ^2.1.2
  provider: ^6.1.2
  url_launcher: ^6.2.2
  uuid: ^4.2.1
#  validators2: ^5.0.0

dev_dependencies:
  analyzer: ^6.4.1
  build_runner: ^2.4.9
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.2
  flutter_native_splash: ^2.4.0
  flutter_test: { sdk: flutter }
  mobx_codegen: ^2.6.1 #

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
